export const postCategories = [
  { title: "Artes", value: "Arts" },
  { title: "Automóveis", value: "Automobiles" },
  { title: "Ciência", value: "Science" },
  { title: "Clima", value: "Weather" },
  { title: "Comida", value: "Food" },
  { title: "Cultura", value: "Culture" },
  { title: "Educação", value: "Education" },
  { title: "Esportes", value: "Sports" },
  { title: "Filmes", value: "Movies" },
  { title: "Moda", value: "Fashion" },
  { title: "Negócios", value: "Business" },
  { title: "Opinião", value: "Opinion" },
  { title: "Política", value: "Politics" },
  { title: "Saúde", value: "Health" },
  { title: "Tecnologia", value: "Technology" },
];
