export const postCategories = [
  { title: "Artes", value: "Arts" },
  { title: "Automóveis", value: "Automobiles" },
  { title: "Ciência", value: "Science" },
  { title: "Clima", value: "Weather" },
  { title: "Comida", value: "Food" },
  { title: "Educação", value: "Education" },
  { title: "Esportes", value: "Sports" },
  { title: "Filmes", value: "Movies" },
  { title: "Livros", value: "Books" },
  { title: "Mundo", value: "World" },
  { title: "Saúde", value: "Health" },
  { title: "Teatro", value: "Theater" },
  { title: "Tecnologia", value: "Technology" },
];
